# Generated by Django 2.2.5 on 2019-09-23 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='measureUnit',
            field=models.CharField(choices=[('grams', 'g'), ('kilograms', 'kg'), ('centiliter', 'cl'), ('liter', 'l')], default='kg', max_length=10),
            preserve_default=False,
        ),
    ]
