# Generated by Django 2.2.5 on 2019-09-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20190923_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measureUnit',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('cl', 'centiliter'), ('l', 'liter')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='measureUnit',
            field=models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('cl', 'centiliter'), ('l', 'liter')], max_length=10),
        ),
    ]
